# Generated by Django 3.2.13 on 2022-09-06 18:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20220428_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
